spring:
  datasource:
    druid:
      url: jdbc:h2:~/data/graduation
      driverClassName: org.h2.Driver
      username: root
      password: a1414914
      validation-query: SELECT now()
      stat-view-servlet:
        login-username: admin
        login-password: admin
        enabled: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2-console
  redis:
    host: 43.138.217.93
    port: 6379
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8

pagehelper:
  helper-dialect: h2
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  banner: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'